# Generated by Django 3.2.10 on 2023-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_json_null_expression_repro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thishasajsonfield',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
